In [1]:
import numpy as np
a = np.arange(15).reshape(3,5)
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [2]:
import numpy as np
a = np.arange(15)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [3]:
import numpy as np
a = np.arange(16).reshape(4,4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [6]:
import numpy as np
a = np.arange(10,60,5).reshape(2,5)
a

array([[10, 15, 20, 25, 30],
       [35, 40, 45, 50, 55]])

In [7]:
import numpy as np 
print (np.array([8, 4, 6, 0, 2]))

[8 4 6 0 2]


In [9]:
a = np.array([[2,4,5],[1,6,3]])
a

array([[2, 4, 5],
       [1, 6, 3]])

In [21]:
A = np.array ([[3,-1,4],[1,5,9]])
print(A)


B = np.array ([[2,4,-5,6],[-1,7,9,3],[3,2,-7,-2]])
print(B)


np.dot(A,B)

[[ 3 -1  4]
 [ 1  5  9]]
[[ 2  4 -5  6]
 [-1  7  9  3]
 [ 3  2 -7 -2]]


array([[ 19,  13, -52,   7],
       [ 24,  57, -23,   3]])

In [29]:
X = np.array ([3,-4,1])

Y = np.array ([5,2,3])

print(X+10)
print(Y*4)
print(X+Y)
print(X*Y)

array([15, -8,  3])

In [30]:
from sklearn import datasets 
iris = datasets.load_iris()
print(iris.filename)

C:\Users\adil\anaconda3\lib\site-packages\sklearn\datasets\data\iris.csv


In [33]:
import numpy as np
iris_data = np.genfromtxt('C:\\Users\\adil\\anaconda3\\lib\\site-packages\\sklearn\\datasets\\data\\iris.csv',
                         delimiter=",", skip_header=1)
print(iris_data)


[[5.1 3.5 1.4 0.2 0. ]
 [4.9 3.  1.4 0.2 0. ]
 [4.7 3.2 1.3 0.2 0. ]
 [4.6 3.1 1.5 0.2 0. ]
 [5.  3.6 1.4 0.2 0. ]
 [5.4 3.9 1.7 0.4 0. ]
 [4.6 3.4 1.4 0.3 0. ]
 [5.  3.4 1.5 0.2 0. ]
 [4.4 2.9 1.4 0.2 0. ]
 [4.9 3.1 1.5 0.1 0. ]
 [5.4 3.7 1.5 0.2 0. ]
 [4.8 3.4 1.6 0.2 0. ]
 [4.8 3.  1.4 0.1 0. ]
 [4.3 3.  1.1 0.1 0. ]
 [5.8 4.  1.2 0.2 0. ]
 [5.7 4.4 1.5 0.4 0. ]
 [5.4 3.9 1.3 0.4 0. ]
 [5.1 3.5 1.4 0.3 0. ]
 [5.7 3.8 1.7 0.3 0. ]
 [5.1 3.8 1.5 0.3 0. ]
 [5.4 3.4 1.7 0.2 0. ]
 [5.1 3.7 1.5 0.4 0. ]
 [4.6 3.6 1.  0.2 0. ]
 [5.1 3.3 1.7 0.5 0. ]
 [4.8 3.4 1.9 0.2 0. ]
 [5.  3.  1.6 0.2 0. ]
 [5.  3.4 1.6 0.4 0. ]
 [5.2 3.5 1.5 0.2 0. ]
 [5.2 3.4 1.4 0.2 0. ]
 [4.7 3.2 1.6 0.2 0. ]
 [4.8 3.1 1.6 0.2 0. ]
 [5.4 3.4 1.5 0.4 0. ]
 [5.2 4.1 1.5 0.1 0. ]
 [5.5 4.2 1.4 0.2 0. ]
 [4.9 3.1 1.5 0.2 0. ]
 [5.  3.2 1.2 0.2 0. ]
 [5.5 3.5 1.3 0.2 0. ]
 [4.9 3.6 1.4 0.1 0. ]
 [4.4 3.  1.3 0.2 0. ]
 [5.1 3.4 1.5 0.2 0. ]
 [5.  3.5 1.3 0.3 0. ]
 [4.5 2.3 1.3 0.3 0. ]
 [4.4 3.2 1.3 0.2 0. ]
 [5.  3.5 1